/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 horloge.gltf 
Author: joseph.deepak19 (https://sketchfab.com/joseph.deepak19)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vol-21-ss-black-leather-6bfb9d695999453aa19172336a76e046
Title: VOL-21 SS BLACK LEATHER
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/horloge.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.003, -0.038, 0.288]} scale={[0.086, 0.086, 0.033]}>
        <group position={[0, 0.089, 0.599]} scale={[6.196, 6.196, 16.308]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials['SS.Chrome.Case']} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['SS.Case']} />
        </group>
        <group position={[0.016, 0.095, 0.317]} scale={[6.196, 6.196, 16.308]}>
          <mesh geometry={nodes.Object_20.geometry} material={materials['SS.Case']} />
          <mesh geometry={nodes.Object_21.geometry} material={materials['SS.Case']} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['SS.Case']} />
          <mesh geometry={nodes.Object_23.geometry} material={materials['SS.Case']} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['SS.Chrome.Case']} />
          <mesh geometry={nodes.Object_25.geometry} material={materials['SS.Case-Horizontal']} />
        </group>
        <mesh geometry={nodes.Object_8.geometry} material={materials['Stainless-Steel.Caseback']} position={[0.026, 0.105, -0.765]} scale={[6.196, 6.196, 16.308]} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['SS.Chrome']} position={[1.361, 0.095, -0.184]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.746, 0.663, 0.663]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Stainless-Steel.008']} position={[-0.004, 0.226, -0.736]} scale={[-22.488, 22.488, 59.19]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['SS.Chrome']} position={[-0.231, 0.096, 0.473]} rotation={[0, 0.006, 0]} scale={[0.121, 0.121, 0.317]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Glass} position={[0.001, 0.1, 0.76]} rotation={[1.571, 0.005, -0.006]} scale={[1.019, 2.681, 1.019]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['SS.Chrome']} position={[0.026, 0.105, -0.81]} rotation={[Math.PI / 2, 0, 0]} scale={[6.196, 16.308, 6.196]} />
      </group>
      <group position={[0.003, -0.021, 0.128]} scale={[0.081, 0.197, 0.197]}>
        <group position={[0.083, -0.019, -0.746]} rotation={[0.028, -0.028, 0.001]} scale={[0.737, 0.326, 0.246]}>
          <group position={[0, -0.26, -0.475]} rotation={[-0.122, 0, 0]} scale={[7.806, 8.518, 11.209]}>
            <mesh geometry={nodes.Object_43.geometry} material={materials['SS.Chrome']} />
            <mesh geometry={nodes.Object_44.geometry} material={materials['Rose-Gold-Chrome.Buckle.001']} />
          </group>
          <mesh geometry={nodes.Object_31.geometry} material={materials['SS.Chrome']} position={[0.002, 0.143, 0.068]} rotation={[0, 0, -Math.PI / 2]} scale={[0.276, 0.32, 0.048]} />
          <mesh geometry={nodes.Object_33.geometry} material={materials['SS.Chrome']} position={[0.002, 0.143, -0.019]} rotation={[Math.PI / 2, 0, 0]} scale={[0.794, 1.143, 0.862]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials['SS.Chrome']} position={[0.005, 1.815, 0.141]} rotation={[-1.519, 0, 0]} scale={[0.252, 0.363, 0.274]} />
          <mesh geometry={nodes.Object_37.geometry} material={materials['SS.Chrome']} position={[0.006, -1.593, 0.077]} rotation={[-1.615, 0, 0]} scale={[0.252, 0.363, 0.274]} />
          <mesh geometry={nodes.Object_39.geometry} material={materials['SS.Chrome']} position={[0.002, 1.131, 0.093]} scale={[7.806, 8.474, 11.243]} />
          <mesh geometry={nodes.Object_41.geometry} material={materials['SS.Chrome']} position={[-0.003, 0.119, 0.179]} rotation={[Math.PI / 2, 0, 0]} scale={[8.035, 11.573, 8.723]} />
          <mesh geometry={nodes.Object_46.geometry} material={materials['SS.Chrome']} position={[0, 0.468, -0.236]} rotation={[0.174, 0, 0]} scale={[7.806, 8.564, 11.174]} />
        </group>
        <group position={[-0.02, -0.14, 0.867]} rotation={[0, -0.029, -Math.PI]} scale={[6.684, 2.761, 2.764]}>
          <mesh geometry={nodes.Object_52.geometry} material={materials['Leather-Gray']} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.Suede} />
          <mesh geometry={nodes.Object_54.geometry} material={materials['Leather-Gray-Side']} />
        </group>
        <group position={[0.003, -2.179, 0.984]} rotation={[-0.014, -0.028, -0.001]} scale={[8.136, 3.361, 3.364]}>
          <mesh geometry={nodes.Object_56.geometry} material={materials['Gray-Thread']} />
          <mesh geometry={nodes.Object_57.geometry} material={materials['Gray-Thread']} />
          <mesh geometry={nodes.Object_58.geometry} material={materials['Gray-Thread']} />
        </group>
        <mesh geometry={nodes.Object_48.geometry} material={materials['Leather-Gray']} position={[0.087, 0.704, -0.47]} rotation={[0.922, -0.009, -3.113]} scale={[6.684, 2.763, 2.762]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['Leather-Gray']} position={[0.063, 0.807, -0.284]} rotation={[1.171, 0.001, -3.11]} scale={[6.684, 2.763, 2.762]} />
      </group>
      <group position={[0.002, -0.031, 0.301]} scale={0.074}>
        <mesh geometry={nodes.Object_60.geometry} material={materials['SS.Chrome']} />
        <mesh geometry={nodes.Object_61.geometry} material={materials['White-Matte.001']} />
      </group>
      <group position={[0.002, -0.031, 0.302]} scale={0.076}>
        <mesh geometry={nodes.Object_65.geometry} material={materials['SS.Chrome']} />
        <mesh geometry={nodes.Object_66.geometry} material={materials['White-Matte.001']} />
      </group>
      <group position={[-0.021, -0.016, 0.302]} rotation={[0, 0, -2.678]} scale={0.101}>
        <mesh geometry={nodes.Object_68.geometry} material={materials['SS.Chrome']} />
        <mesh geometry={nodes.Object_69.geometry} material={materials['White-Matte.001']} />
      </group>
      <group position={[0.004, -0.013, 0.3]} scale={0.526}>
        <mesh geometry={nodes.Object_73.geometry} material={materials['SS.Chrome']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.ChronoWhite} />
      </group>
      <group position={[0.002, -0.074, 0.301]} scale={0.076}>
        <mesh geometry={nodes.Object_76.geometry} material={materials['SS.Chrome']} />
        <mesh geometry={nodes.Object_77.geometry} material={materials['SS.Chrome']} />
      </group>
      <group position={[0.002, -0.031, 0.3]} rotation={[Math.PI / 2, -0.514, 0]} scale={0.526}>
        <mesh geometry={nodes.Object_79.geometry} material={materials['Dial-White_Anisotropic.001']} />
        <mesh geometry={nodes.Object_80.geometry} material={materials['SS.Chrome']} />
        <mesh geometry={nodes.Object_81.geometry} material={materials['White.Trim.001']} />
      </group>
      <mesh geometry={nodes.Object_27.geometry} material={materials['SS.Chrome.Case']} position={[0.002, -0.031, 0.313]} rotation={[Math.PI / 2, 0, 0]} scale={[0.537, 0.537, 0.541]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials['SS.Chrome']} position={[0.002, -0.032, 0.305]} scale={0.076} />
      <mesh geometry={nodes.Object_71.geometry} material={materials['SS.Chrome']} position={[-0.008, 0.021, 0.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.526} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Black} position={[-0.015, 0.003, 0.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.526} />
    </group>
  )
}

useGLTF.preload('/horloge.gltf')
