/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 watch.gltf 
Author: joseph.deepak19 (https://sketchfab.com/joseph.deepak19)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vol-13-yg-gold-57a8dcbfa8dc478194635c4625e85ce7
Title: VOL-13 YG Gold
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  
  const { nodes, materials } = useGLTF('/watch.gltf')

  return (
    <group {...props} dispose={null}>
      <group position={[0.003, -0.038, 0.288]} scale={[0.086, 0.086, 0.033]}>
        <group position={[0, 0.089, 0.599]} scale={[6.196, 6.196, 16.308]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials['Chrome.Case']} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Case} />
        </group>
        <group position={[0.016, 0.095, 0.317]} scale={[6.196, 6.196, 16.308]}>
          <mesh geometry={nodes.Object_20.geometry} material={materials.Case} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Case} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.Case} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.Case} />
          <mesh geometry={nodes.Object_24.geometry} material={materials['Chrome.Case']} />
          <mesh geometry={nodes.Object_25.geometry} material={materials['Case-Horizontal']} />
        </group>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Caseback} position={[0.026, 0.105, -0.765]} scale={[6.196, 6.196, 16.308]} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Chrome} position={[1.361, 0.095, -0.184]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.746, 0.663, 0.663]} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Chrome} position={[-0.004, 0.226, -0.736]} scale={[-22.488, 22.488, 59.19]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Chrome} position={[-0.231, 0.096, 0.473]} rotation={[0, 0.006, 0]} scale={[0.121, 0.121, 0.317]} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Glass} position={[0.001, 0.1, 0.76]} rotation={[1.571, 0.005, -0.006]} scale={[1.019, 2.681, 1.019]} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Chrome} position={[0.026, 0.105, -0.81]} rotation={[Math.PI / 2, 0, 0]} scale={[6.196, 16.308, 6.196]} />
      </group>
      <group position={[0.002, -0.031, 0.301]} scale={0.074}>
        <mesh geometry={nodes.Object_31.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['White-Matte.001']} />
      </group>
      <group position={[0.002, -0.031, 0.302]} scale={0.076}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['White-Matte.001']} />
      </group>
      <group position={[-0.021, -0.016, 0.302]} rotation={[0, 0, -2.678]} scale={0.101}>
        <mesh geometry={nodes.Object_39.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['White-Matte.001']} />
      </group>
      <group position={[0.004, -0.013, 0.3]} scale={0.526}>
        <mesh geometry={nodes.Object_44.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Chrono-Dial-Green.001']} />
      </group>
      <group position={[0.002, -0.074, 0.301]} scale={0.076}>
        <mesh geometry={nodes.Object_47.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Chrome} />
      </group>
      <group position={[0.002, -0.031, 0.3]} rotation={[Math.PI / 2, -0.514, 0]} scale={0.526}>
        <mesh geometry={nodes.Object_50.geometry} material={materials['Dial-Green_Anisotropic.001']} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['Green.Trim.001']} />
      </group>
      <group position={[0.006, -0.027, 0.133]} scale={[0.08, 0.194, 0.194]}>
        <group position={[-0.038, 0.073, 0.832]} scale={[6.595, 2.724, 2.724]}>
          <mesh geometry={nodes.Object_59.geometry} material={materials['Buckle-Chrome']} />
          <mesh geometry={nodes.Object_60.geometry} material={materials['Chrome.Buckle.Arkouda']} />
        </group>
        <group position={[-0.038, -0.702, -0.112]} scale={[6.595, 2.724, 2.724]}>
          <mesh geometry={nodes.Object_62.geometry} material={materials.Strap} />
          <mesh geometry={nodes.Object_63.geometry} material={materials['Chrome.Strap']} />
        </group>
        <mesh geometry={nodes.Object_57.geometry} material={materials.Chrome} position={[-0.041, -0.008, -0.72]} rotation={[Math.PI / 2, 0, 0]} scale={[6.789, 2.804, 2.804]} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Chrome} position={[-0.038, 0.083, 0.791]} scale={[6.595, 2.724, 2.724]} />
      </group>
      <mesh geometry={nodes.Object_27.geometry} material={materials['Chrome.Case']} position={[0.002, -0.031, 0.313]} rotation={[Math.PI / 2, 0, 0]} scale={[0.537, 0.537, 0.541]} />
      <mesh geometry={nodes.Object_29.geometry} material={materials['Chrome.Case']} position={[0.002, -0.04, 0.064]} rotation={[1.016, Math.PI / 2, 0]} scale={0.262} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Chrome} position={[0.002, -0.032, 0.305]} scale={0.076} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Chrome} position={[-0.008, 0.021, 0.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.526} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.Chrome} position={[-0.015, 0.003, 0.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.526} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Chrome} position={[0, -0.028, -0.01]} rotation={[0, 0, -Math.PI / 2]} scale={[0.017, 0.022, 0.002]} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.Chrome} position={[0, -0.028, -0.014]} rotation={[Math.PI / 2, 0, 0]} scale={0.054} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.Chrome} position={[0.001, 0.076, -0.007]} rotation={[-1.521, 0, 0]} scale={0.017} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.Chrome} position={[0.001, -0.136, -0.01]} rotation={[-1.613, 0, 0]} scale={0.017} />
    </group>
  )
}

useGLTF.preload('/watch.gltf')
